### ISSUE TITLE
Changing wreckfest server configuration

### ISSUE THREAD

**Issue by xenicle** [OpenSourceLAN/gameservers-docker#22]
Hi !

I try to update the container when changing configuration in wreckfest/start_wreckfest.sh like server name etc
I tried to make "./build wreckfest" in root folder and started server with "./start_server.sh wreckfest" and the changes not reflected...
I needed to "docker system prune -a" and rebuild with "./build wreckfest" for the change take effect.

Or is there another way ?

**Comment by sirsquidness** [comment]
Hiya!

There is not enough information in this to tell you what to do differently. Some more specifics about which files you're editing, and what commands you are running to show that no changes were made.

If you're making changes to the files included in the docker build, then docker will recreate the image when the build shell script calls it. 

Instead of using the `start_server.sh` script, you might try running it manually and making sure the previous instance is deleted first:

```
docker rm -f wreckfest_1
docker run -it --net=host --rm --name wreckfest_1 wreckfest
```

**Comment by xenicle** [comment]
Hi !

I can confirm when making 

`docker rm -f wreckfest_1
docker run -it --net=host --rm --name wreckfest_1 wreckfest`

after "./build.sh wreckfest"

The change make in config file have been made to the server, sorry for my misunderstood of docker (I'll try to learn it...)

**Comment by sirsquidness** [comment]
Glad you got it working, enjoy! :) Feel free to re-open this issue if you run in to any other problems
